---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1cf54he0f5mggkvkurux4u44rn5dmylc2g74cf703swj0yyfqms0sgczm80
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1cf54he0f5mggkvkurux4u44rn5dmylc2g74cf703swj0yyfqms0sgczm80
