---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "192.168.1.50"
  METALLB_LB_RANGE: "192.168.1.51-192.168.1.70"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.51"
  METALLB_INGRESS_ADDR: "192.168.1.52"
