apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vJmcRC2NK5XGJnGoIiP7iE/NV/YSqOC2rUqhQBSPbaAChgrE,iv:yoEtOnoW8K1oQ47ZaZQgwysRELuDkJ8gNWwVcTne3tY=,tag:pn0w2UEmFkjcYC8iRnn2yg==,type:str]
    credentials.json: ENC[AES256_GCM,data:XsDGCMClG78mdubHDqByOgzKM5ayE4cqXZ9uYsbje5JoVW21d3BU/FtV55lNTO0jNrxsS+6/hIv2rfuhLgNx5KVZqvwvGKCpBehlAYwlxAq1Z4M3w+rq88wSkLxXhU68XHrWGzERcL73abYKqKg9ILzYDx3rWzdoXbqqNIL0LBUaqf6FkuVtzoNyQUz2rsdGrG3aAbpVMIBumEo5M5aESvzKSkweFkrXBfDIpeqhbA==,iv:/4LNyL6oOr0Gt/dRMNo5puwF8/MPm5mX3T2tAkJYBMg=,tag:yOd+YUVUuBtpYOuP5q/OFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cf54he0f5mggkvkurux4u44rn5dmylc2g74cf703swj0yyfqms0sgczm80
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cVI1Nno2bjFmQjNLSWxK
            ZzN5YUQzeFdtemNtS2tGL05CYjZmNEdSb2cwCnAyemREVGs1NGpTV05TL1YvcERD
            WDRQem1iTW1wTmpYUDhzNFlJVitVV1kKLS0tIGpYN1NDaEE3bXJCT04xd3NVYjhG
            M0NxQWo4bEV4TERJRlJyV0JJSDg2MDAKcwVnfKYk3bvTO55D7s1ofy6knXlHJAWI
            4xPsp8pYF/EAWt24lfr/oDnuQoDsZapf3rEkvo658D0P8PdLPhDn5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T01:57:14Z"
    mac: ENC[AES256_GCM,data:bxMGMEcP+ZoNWvmiyDrkmXK8ORZmy3Z1ufo2vzjnk6ZuZUH4i9OwS6XtcCh1N4AJEs/tSsPiRDv9Io8NtHdxDr/tb3eWToCNtT/Z3tAHYpMUU/+oZuqW47Wv5paMhqVwM8Z6k5Vds9rJvr0pp3ppuGCKOvKNgDdttzOfLi44f2g=,iv:bhJynuxS4gll7i2YtmhoNDPq17HK42eBv+egZkWJGhg=,tag:w85Ujr5DhZ8uzzmU+xDxqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
